export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_GITHUB_USERNAME = 'SET_GITHUB_USERNAME';
export const GET_GITHUB_USER = 'GET_GITHUB_USER';
export const CLEAR_GITHUB_USER = 'CLEAR_USER';
export const SET_LOADING = 'SET_LOADING';
